services:

  minio:

    image: quay.io/minio/minio:latest

    container_name: minio

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio_data:/data


  minio-init:

    image: quay.io/minio/mc:latest

    container_name: minio-init

    depends_on:
      - minio

    entrypoint: >
      /bin/sh -c "
      sleep 5;

      mc alias set local
      http://minio:9000
      ${MINIO_ROOT_USER}
      ${MINIO_ROOT_PASSWORD};

      mc mb --ignore-existing
      local/${BRONZE_BUCKET};

      mc mb --ignore-existing
      local/${SILVER_BUCKET};

      mc mb --ignore-existing
      local/${GOLD_BUCKET};

      mc admin user add
      local
      ${MINIO_SPARK_USER}
      ${MINIO_SPARK_PASSWORD}
      || true;

      mc admin policy attach
      local
      readwrite
      --user ${MINIO_SPARK_USER};

      exit 0;
      "


  postgres:

    image: postgres:16

    container_name: postgres

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      AIRFLOW_DB: ${AIRFLOW_DB}
      AIRFLOW_DB_USER: ${AIRFLOW_DB_USER}
      AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/02-init.sql

    restart: unless-stopped


  spark:

    build:
      context: ./spark
      dockerfile: Dockerfile

    container_name: spark

    working_dir: /opt/spark-apps

    volumes:
      - ./spark:/opt/spark-apps
      - ./config:/opt/spark-apps/config

    depends_on:
      - minio
      - postgres

    command: tail -f /dev/null

    environment:
      PYTHONPATH: /opt/spark-apps

      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_SPARK_USER}
      MINIO_SECRET_KEY: ${MINIO_SPARK_PASSWORD}

      BRONZE_BUCKET: ${BRONZE_BUCKET}
      SILVER_BUCKET: ${SILVER_BUCKET}
      GOLD_BUCKET: ${GOLD_BUCKET}

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


  dbt:

    build:
      context: ./dbt
      dockerfile: Dockerfile

    container_name: dbt

    working_dir: /usr/app/dbt

    volumes:
      - ./dbt:/usr/app/dbt

    depends_on:
      - postgres

    environment:
      DBT_PROFILES_DIR: /usr/app/dbt

      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    command: tail -f /dev/null


  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    container_name: airflow

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB}

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}

    command: >
      bash -c "airflow db migrate &&
      airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Admin --lastname User --role Admin --email admin@example.com || true;
      airflow webserver &
      airflow scheduler"


  ingestion:

    build:
      context: .
      dockerfile: ./ingestion/Dockerfile

    container_name: ingestion

    working_dir: /app

    depends_on:
      - minio
      - postgres

    environment:
      PYTHONPATH: /app

      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      BRONZE_BUCKET: ${BRONZE_BUCKET}
      SILVER_BUCKET: ${SILVER_BUCKET}
      GOLD_BUCKET: ${GOLD_BUCKET}

      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    command: tail -f /dev/null


volumes:

  minio_data:

  postgres_data: